setup_venv: Hardcode the version of setuptools.
This works around a regression in setuptools 28.3.0 that caused errors like this:

  Running setup.py install for cchardet ... error
    Complete output from command /srv/zulip-venv-cache/8e84e610d0834b666d337a42b7cd5085b13331af/zulip-venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9f_SEG/cchardet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JdIYOA-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/zulip-venv-cache/8e84e610d0834b666d337a42b7cd5085b13331af/zulip-venv/include/site/python2.7/cchardet --no-ml:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --no-ml not recognized

Basically, setuptools was passing the `--no-ml` option to every
dependency being installed, not just talon (which requests that
option) as it should have.